const seed = [
  {
    id: 1,
    title: "The song of Achilles",
    authors: ["Madeline Miller"],
    price: 1014,
    stock: 0,
    numberOfOrders: 0,
    rating: 4.32,
    images: [
      "https://http2.mlstatic.com/D_NQ_NP_2X_883863-MLA49286758275_032022-F.webp",
    ],
    genres: ["novella"],
    pages: 416,
    weight: 300,
    publishingHouse: "Puck",
    published: "September 20, 2011",
    language: "En",
    isbn: "978-987413201-7",
    description:
      "Achilles, the best of all the Greeks, son of the cruel sea goddess Thetis and the legendary king Peleus, is strong, swift, and beautiful, irresistible to all who meet him. Patroclus is an awkward young prince, exiled from his homeland after an act of shocking violence. Brought together by chance, they forge an inseparable bond, despite risking the gods wrath. They are trained by the centaur Chiron in the arts of war and medicine, but when word comes that Helen of Sparta has been kidnapped, all the heroes of Greece are called upon to lay siege to Troy in her name. Seduced by the promise of a glorious destiny, Achilles joins their cause, and torn between love and fear for his friend, Patroclus follows. Little do they know that the cruel Fates will test them both as never before and demand a terrible sacrifice.",
    reviews: [
      {
        idUser: 1,
        author: "Sean Barrs",
        score: 4,
        content:
          "Madeline Miller did what the movie producers of the film Troy (2004) were too cowardly to do; she stayed true to the homosexuality of Homers Iliad rather than writing a censored version of the story which stank of homophobia. Achilles and Patroclus were passionately in love, which resulted in their respective destructions. They were not cousins or man at arms, but soul mates. The watering down of this in the film Troy was an insult to the LGBT community. Nothing more. Nothing less. The attraction between these two men wasnt something that was rushed and squandered. It was built up, ever so slowly, and delivered eloquently. The two were friends from boyhood, and Patroclus was enamoured by Achilles after just one glance. He didnt want to be parted from him. The two grew up together, they fought together, they learnt together and they developed together. They became inseparable and reliant on each other. Their sexual relationship just matured as they did it; it was the most natural thing in the world. Like all relationships, there were issues. The two werent without their differences. They clashed and quarrelled but only because they truly cared for each other. Patroclus wanted to end the war, and Achilles didnt think the fight was worthy of his name: he wanted a bigger war to fight in. So, Patroclus, in his most bravest and stupid move goes against his lovers wish and tries to end the war with a stroke of his sword. But he is no Achilles: he is not a god of war. He was out of his depth, outmatched and doomed",
        createdAt: "October 26, 2022",
      },
      {
        idUser: 2,
        author: "Matias Dominguez",
        score: 5,
        content:
          "Madeline Miller did what the movie producers of the film Troy (2004) were too cowardly to do; she stayed true to the homosexuality of Homers Iliad rather than writing a censored version of the story which stank of homophobia. Achilles and Patroclus were passionately in love, which resulted in their respective destructions. They were not cousins or man at arms, but soul mates. The watering down of this in the film Troy was an insult to the LGBT community. Nothing more. Nothing less",
        createdAt: "October 26, 2022",
      },
      {
        idUser: 3,
        author: "Matias Dominguez",
        score: 5,
        content:
          "Madeline Miller did what the movie producers of the film Troy (2004) were too cowardly to do; she stayed true to the homosexuality of Homers Iliad rather than writing a censored version of the story which stank of homophobia. Achilles and Patroclus were passionately in love, which resulted in their respective destructions. They were not cousins or man at arms, but soul mates. The watering down of this in the film Troy was an insult to the LGBT community. Nothing more. Nothing less",
        createdAt: "October 26, 2022",
      },
      {
        idUser: 4,
        author: "Matias Dominguez",
        score: 2,
        content:
          "Madeline Miller did what the movie producers of the film Troy (2004) were too cowardly to do; she stayed true to the homosexuality of Homers Iliad rather than writing a censored version of the story which stank of homophobia. Achilles and Patroclus were passionately in love, which resulted in their respective destructions. They were not cousins or man at arms, but soul mates. The watering down of this in the film Troy was an insult to the LGBT community. Nothing more. Nothing less",
        createdAt: "October 26, 2022",
      },
    ],
  },
  {
    id: 2,
    title: "The name of the wind",
    authors: ["Patrick Rothfuss"],
    price: 2899,
    stock: 1,
    numberOfOrders: 1,
    rating: 3.85,
    images: [
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1270352123i/186074.jpg",
    ],
    genres: ["novella"],
    weight: 559,
    publishingHouse: "Salamanca",
    published: "March 27, 2007",
    pages: 662,
    language: "En",
    isbn: "222",
    description:
      "As the novel begins, the reader hears an old storyteller speaking of a famous old wizard called Taborlin the Great, who was captured by evil beings called the Chandrian. Escaping them, Taborlin fell from a great height—but since he knew the Name of the Wind, he called it and the Wind came and set him down safely. In later parts of the book, characters are often skeptical of such stories. Some kinds of magic are taught in the university as academic disciplines and have daily-life applications (those who can afford it are able to buy magical lamps, for example, much better than the candles used by poorer people). However, most of the population does not have reliable knowledge of the magical disciplines and many still doubt that magicians can truly call upon the Wind. The Chandrian—whose appearance is supposedly heralded by flames turning blue—are often dismissed as mythical bogeymen.",
    rewies: [],
  },
  {
    id: 3,
    title: "The house of cerulean sea",
    authors: ["T J Klune"],
    price: 1116,
    stock: 2,
    numberOfOrders: 2,
    rating: 4.5,
    images: [
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1569514209i/45047384.jpg",
    ],
    genres: ["novella"],
    pages: 334,
    weight: 467,
    publishingHouse: "The new books",
    published: "March 16, 2020",
    language: "En",
    isbn: "333",
    description:
      "Linus Baker leads a quiet, solitary life. At forty, he lives in a tiny house with a devious cat and his old records. As a Case Worker at the Department in Charge Of Magical Youth, he spends his days overseeing the well-being of children in government-sanctioned orphanages. When Linus is unexpectedly summoned by Extremely Upper Management he's given a curious and highly classified assignment: travel to Marsyas Island Orphanage, where six dangerous children reside: a gnome, a sprite, a wyvern, an unidentifiable green blob, a were-Pomeranian, and the Antichrist. Linus must set aside his fears and determine whether or not they’re likely to bring about the end of days.But the children aren’t the only secret the island keeps. Their caretaker is the charming and enigmatic Arthur Parnassus, who will do anything to keep his wards safe. As Arthur and Linus grow closer, long-held secrets are exposed, and Linus must make a choice: destroy a home or watch the world burn.An enchanting story, masterfully told, The House in the Cerulean Sea is about the profound experience of discovering an unlikely family in an unexpected place—and realizing that family is yours.",
    rewies: [],
  },
  {
    id: 4,
    title: "1984",
    authors: ["George Orwell"],
    price: 748,
    stock: 3,
    numberOfOrders: 3,
    rating: 2.63,
    images: [
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1657781256i/61439040.jpg",
    ],
    genres: ["novella"],
    pages: 400,
    weight: 474,
    publishingHouse: "We know about you",
    published: "January 1, 1949",
    language: "En",
    isbn: "444",
    description:
      "This edition features George Orwells best-known novels—1984 and Animal Farm—with an introduction by Christopher Hitchens.In 1984, London is a grim city where Big Brother is always watching you and the Thought Police can practically read your mind. Winston Smith joins a secret revolutionary organisation called The Brotherhood, dedicated to the destruction of the Party. Together with his beloved Julia, he hazards his life in a deadly match against the powers that be.Animal Farm is Orwell’s classic satire of the Russian Revolution - an account of the bold struggle, initiated by the animals, that transforms Mr. Jones’s Manor Farm into Animal Farm - a wholly democratic society built on the credo that All Animals Are Created Equal. But are they? AUTHOR: George Orwell (1903-1950) was born in India and served with the Imperial Police in Burma before joining the Republican Army in the Spanish Civil War. Orwell was the author of six novels as well as numerous essays and nonfiction works.",
    rewies: [],
  },
  {
    id: 5,
    title: "High fidelity",
    authors: ["Nick Hornby"],
    price: 1499,
    stock: 4,
    numberOfOrders: 4,
    rating: 3.92,
    images: [
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327928082i/285092.jpg",
    ],
    genres: ["novella"],
    pages: 400,
    weight: 474,
    publishingHouse: "Lovestorys4eve",
    published: "January 1, 1995",
    language: "En",
    isbn: "444",
    description:
      "This edition features George Orwells best-known novels—1984 and Animal Farm—with an introduction by Christopher Hitchens.In 1984, London is a grim city where Big Brother is always watching you and the Thought Police can practically read your mind. Winston Smith joins a secret revolutionary organisation called The Brotherhood, dedicated to the destruction of the Party. Together with his beloved Julia, he hazards his life in a deadly match against the powers that be.Animal Farm is Orwell’s classic satire of the Russian Revolution - an account of the bold struggle, initiated by the animals, that transforms Mr. Jones’s Manor Farm into Animal Farm - a wholly democratic society built on the credo that All Animals Are Created Equal. But are they? AUTHOR: George Orwell (1903-1950) was born in India and served with the Imperial Police in Burma before joining the Republican Army in the Spanish Civil War. Orwell was the author of six novels as well as numerous essays and nonfiction works.",
    rewies: [],
  },
  {
    id: 6,
    title: "The Art of War",
    authors: ["Sun tzu"],
    price: 499,
    stock: 5,
    numberOfOrders: 5,
    rating: 1.7,
    images: [
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1630683326i/10534.jpg",
    ],
    genres: ["novella"],
    pages: 143,
    weight: 169,
    publishingHouse: "I will kill you moe wiiii",
    published: "January 1, 401",
    language: "En",
    isbn: "666",
    description:
      "Twenty-Five Hundred years ago, Sun Tzu wrote this classic book of military strategy based on Chinese warfare and military thought. Since that time, all levels of military have used the teaching on Sun Tzu to warfare and civilization have adapted these teachings for use in politics, business and everyday life. The Art of War is a book which should be used to gain advantage of opponents in the boardroom and battlefield alike.",
    rewies: [],
  },
  {
    id: 7,
    title: "siddhartha",
    authors: ["Hermann Hesse"],
    price: 899,
    stock: 6,
    numberOfOrders: 6,
    rating: 1.7,
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSI2PVQlcrlBaoQOewxFyCqMs6Kb1WFU_9tUw&usqp=CAU",
    ],
    genres: ["novella"],
    pages: 152,
    weight: 180,
    publishingHouse: "God its that you?",
    published: "January 1, 1922",
    language: "En",
    isbn: "666",
    description:
      "Herman Hesse's classic novel has delighted, inspired, and influenced generations of readers, writers, and thinkers. In this story of a wealthy Indian Brahmin who casts off a life of privilege to seek spiritual fulfillment. Hesse synthesizes disparate philosophies--Eastern religions, Jungian archetypes, Western individualism--into a unique vision of life as expressed through one man's search for true meaning.",
    rewies: [],
  },
  {
    id: 8,
    title: "Complete Works of Oscar Wilde",
    authors: ["Oscar Wilde"],
    price: 2499,
    stock: 7,
    numberOfOrders: 7,
    rating: 4.78,
    images: [
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388610522i/5289.jpg",
    ],
    genres: ["novella"],
    pages: 1270,
    weight: 1504,
    publishingHouse: "All classics",
    published: "January 1, 1908",
    language: "En",
    isbn: "777",
    description:
      "In print since 1948, this is a single-volume collection of Oscar Wilde's texts. It contains his only novel, The Portrait of Dorian Gray as well as his plays, stories, poems, essays and letters. Illustrated with many photographs, the book includes introductions to each section by Wilde's grandon, Merlin Holoand, Owen Dudley Edwards, Declan Kibertd and Terence Brown. A comprehensive bibliography of works by and about Oscar Wilde together with a chronological table of his life and work are also included.",
    rewies: [],
  },
  {
    id: 9,
    title: "The picture of Dorian Gray",
    authors: ["Oscar Wilde"],
    price: 999,
    stock: 8,
    numberOfOrders: 8,
    rating: 4.12,
    images: [
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1546103428i/5297.jpg",
    ],
    genres: ["novella"],
    pages: 272,
    weight: 322,
    publishingHouse: "All classics",
    published: "June 1, 1890",
    language: "En",
    isbn: "888",
    description:
      "Oscar Wildes only novel is the dreamlike story of a young man who sells his soul for eternal youth and beauty. In this celebrated work Wilde forged a devastating portrait of the effects of evil and debauchery on a young aesthete in late-19th-century England. Combining elements of the Gothic horror novel and decadent French fiction, the book centers on a striking premise: As Dorian Gray sinks into a life of crime and gross sensuality, his body retains perfect youth and vigor while his recently painted portrait grows day by day into a hideous record of evil, which he must keep hidden from the world. For over a century, this mesmerizing tale of horror and suspense has enjoyed wide popularity. It ranks as one of Wilde's most important creations and among the classic achievements of its kind.",
    rewies: [],
  },
  {
    id: 10,
    title: "Al Final mueren los dos",
    authors: ["Adam Silvera"],
    price: 1363,
    stock: 9,
    numberOfOrders: 9,
    rating: 3.57,
    images: ["https://i.postimg.cc/wvYB1Z42/al-final-los-dos-mueren.jpg"],
    genres: ["novella"],
    pages: 346,
    weight: 410,
    publishingHouse: "LGBT loves Storys",
    published: "September 5, 2017",
    language: "Es",
    isbn: "999",
    description:
      "Imagina un mundo en el que una organización les avisa a las personas la inminencia de su muerte. Imagina que empezó la cuenta regresiva. Imagina cómo vivirías tu vida¿ en solo un día. ¿Estarías listo para decir adiós? Al final mueren los dos es un canto a la fuerza arrolladora de la vida, que transformará para siempre tu forma de comprender el tiempo, la amistad y el amor.",
    rewies: [],
  },
  {
    id: 11,
    title: "A Little Life",
    authors: ["Hanya Yanagihara"],
    price: 1232,
    stock: 10,
    numberOfOrders: 10,
    rating: 4.34,
    images: [
      "https://m.media-amazon.com/images/I/518ewPPStwL._SX323_BO1,204,203,200_.jpg",
    ],
    genres: ["novella"],
    pages: 720,
    weight: 853,
    publishingHouse: "LGBT loves Storys",
    published: "March 10, 2015",
    language: "En",
    isbn: "11000",
    description:
      "A Little Life follows four college classmates—broke, adrift, and buoyed only by their friendship and ambition—as they move to New York in search of fame and fortune. While their relationships, which are tinged by addiction, success, and pride, deepen over the decades, the men are held together by their devotion to the brilliant, enigmatic Jude, a man scarred by an unspeakable childhood trauma. A hymn to brotherly bonds and a masterful depiction of love in the twenty-first century, Hanya Yanagiharas stunning novel is about the families we are born into, and those that we make for ourselves.",
    rewies: [],
  },
  {
    id: 12,
    title: "The Seven Husbands of Evelyn Hugo",
    authors: ["Taylor Jenkins Reid"],
    price: 1499,
    stock: 11,
    numberOfOrders: 11,
    rating: 4.46,
    images: [
      "https://m.media-amazon.com/images/I/41x4eg5KyGL._SX320_BO1,204,203,200_.jpg",
    ],
    genres: ["novella"],
    pages: 389,
    weight: 461,
    publishingHouse: "We got you cover P%",
    published: "June 13, 2017",
    language: "En",
    isbn: "11000",
    description:
      "Imagina un mundo en el que una organización les avisa a las personas la inminencia de su muerte. Imagina que empezó la cuenta regresiva. Imagina cómo vivirías tu vida¿ en solo un día. ¿Estarías listo para decir adiós? Al final mueren los dos es un canto a la fuerza arrolladora de la vida, que transformará para siempre tu forma de comprender el tiempo, la amistad y el amor.",
    rewies: [],
  },
];
export default seed;
